#!/usr/bin/env bash

topic="ntfy.sh/kostas_at_molev212"
cmd_to_run=$@

function success { 
curl \
  -H "Title: Process completed." \
  -H "Tags: heavy_check_mark, tada" \
  -d "Success for \"${cmd_to_run}\".
Ran for $(($SECONDS/60)) minutes and $((SECONDS%60)) seconds." \
  $topic
}

function fail {
curl \
  -H "Title: Process failed." \
  -H "Tags: facepalm,skull" \
  -d "Failure for \"${cmd_to_run}\"." \
  $topic
}

# Run the command and sent the appropriate message
$@ && success || fail
